displayed-name: application-git-dev
server:
  port: 8081
spring:
  jpa:
    show-sql: true
  application:
    name: customerAppli
  mvc:
    hiddenmethod:
      filter:
        enabled: true

spring.datasource:
  url: jdbc:h2:mem:db
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
security:
  ignored: /**
